apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apiservice
  name: apiservice
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: apiservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apiservice
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: apiservice-env
        image: '{{ .Values.images.apiservice }}'
        imagePullPolicy: Always
        name: apiservice
        ports:
        - containerPort: 8080
        - containerPort: 8443
      terminationGracePeriodSeconds: 180