apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cache
  name: cache
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: cache
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: cache-env
        image: '{{ .Values.images.cache }}'
        imagePullPolicy: Always
        name: cache
        ports:
        - containerPort: 6379
      terminationGracePeriodSeconds: 180