bases:
- ../../base

namespace: production
namePrefix: production-

patches:
  - target:
      kind: Deployment
      name: helloworld
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 8
