---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  selector:
    app: helloworld
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8000
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: helloworld-loadbalancer
# spec:
#   selector:
#     app: helloworld
#   type: LoadBalancer
#   ports:
#   - name: http
#     port: 80
#     targetPort: 8000
#     nodePort: 31000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: helloworld-nodeport
# spec:
#   selector:
#     app: helloworld
#   type: NodePort
#   ports:
#   - name: http
#     port: 80
#     targetPort: 8000
#     nodePort: 32555